# @package _global_
module:
  _target_: emg2qwerty.lightning.CNN_LSTM_CTCModule
  in_features: 528 # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  conv_kernel_size: 3
  conv_temporal_stride: 2
  lstm_hidden_size: 400
  lstm_num_layers: 1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000 # 4 sec windows for 2kHz EMG
  padding: [1800, 200] # 900ms past context, 100ms future context
