# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConv_LSTM_CTCModule
  in_features: 528 # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32 # Total temporal receptive field of 125 samples given 4 layers
  lstm_hidden_size: 400
  lstm_num_layers: 2 #past: 5, 1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000 # 4 sec windows for 2kHz EMG
  padding: [1800, 200] # 900ms past context, 100ms future context
